### ISSUE TITLE
上传不是图片的文件  递归没有结束的标志

### ISSUE THREAD

**Issue by json-HB** [webyom/yom-file-uploader#1]
https://github.com/webyom/yom-file-uploader/blob/0535c947f6f2e5eedf80a4194def080b22aff7e7/src/yom-file-uploader.js#L342-L353

if(!(/^image\//i).test(file.type)) {
				fixedFiles.push(file);
				if(i == files.length - 1) {
					callback(fixedFiles);
					return;
				  } else {
					readFile(++i);
				  }
			}

**Comment by webyom** [comment]
@json-HB 提个PR给我
